---
- hosts: all
  become: yes
  become_method: sudo
  gather_facts: yes

  tasks:

  - name: install pip
    easy_install: name=pip state=latest

  - name: install boto
    pip: name=boto3

  - name: copy file from s3
    aws_s3:
      aws_access_key: "AKIAJSRC6OBXIP7FH3HQ"
      aws_secret_key: "0dzdnAiNVP4sOaOgH84PNG9PCGR5ktI7lhTREYzc"
      bucket: jenkins-artifacts-rajesh
      object: sample.war
      dest: /opt/tomcat/webapps/sample.war
      mode: get

